print('Podaj imię: ')
first_name = input()
print('Podaj nazwisko: ')
second_name = input()
print('Podaj miasto: ')
city = input()
print('Podaj kod pocztowy: ')
post_code = input()
print('Podaj ulicę: ')
street = input()
print('Podaj nr domu: ')
number_home = input()
print('Podaj nr mieszkania: ')
number_apartment = input()